### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by penguinbear** [giannisnik/cnn-graph-classification#2]
Hi giannisnik,

Thanks for your kind sharing code!

As I run "python main.py" without any code change, I get a RecursionError. The whole trace is posted below, could you pls help check?
--------------------------------
$ python main.py 
Computing graph maps
Number of communities:  2590
Average size: 7.53
Starting cross-validation
	Create model
Traceback (most recent call last):
  File "main.py", line 280, in <module>
    main()
  File "main.py", line 101, in main
    model = CNN(input_size=args.n_filters, hidden_size=args.hidden_size, n_classes=np.unique(y).size, d=args.d, n_kernels=n_kernels, max_n_communities=max_n_communities)
  File "/Users/polarbear/Personal/NU/MSiA/Courses/Summer_Quarter_2018/OnPoint_Internship/cnn-graph-classification-master/kcnn/model.py", line 13, in __init__
    self.init_weights()
  File "/Users/polarbear/Personal/NU/MSiA/Courses/Summer_Quarter_2018/OnPoint_Internship/cnn-graph-classification-master/kcnn/model.py", line 16, in init_weights
    xavier_uniform(self.conv.weight.data)
  File "/Users/polarbear/Personal/NU/MSiA/Courses/Summer_Quarter_2018/OnPoint_Internship/cnn-graph-classification-master/kcnn/init.py", line 43, in xavier_uniform
    xavier_uniform(tensor.data, gain=gain)
  File "/Users/polarbear/Personal/NU/MSiA/Courses/Summer_Quarter_2018/OnPoint_Internship/cnn-graph-classification-master/kcnn/init.py", line 43, in xavier_uniform
    xavier_uniform(tensor.data, gain=gain)
  File "/Users/polarbear/Personal/NU/MSiA/Courses/Summer_Quarter_2018/OnPoint_Internship/cnn-graph-classification-master/kcnn/init.py", line 43, in xavier_uniform
    xavier_uniform(tensor.data, gain=gain)
  [Previous line repeated 985 more times]
  File "/Users/polarbear/Personal/NU/MSiA/Courses/Summer_Quarter_2018/OnPoint_Internship/cnn-graph-classification-master/kcnn/init.py", line 42, in xavier_uniform
    if isinstance(tensor, Variable):
RecursionError: maximum recursion depth exceeded
--------------

Thanks!

**Comment by penguinbear** [comment]
@giannisnik ,

Thanks for your kind reply!
My PyTorch is 0.4.0
I'll try to downgrade it to 0.3.0.
Thank you and keep you updated.

**Comment by penguinbear** [comment]
@giannisnik 

Thank you!
It works as I downgraded my torch to 0.3.
